version: "3.9"

services:
  kibana:
    image: kibana:7.17.6
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch

  dejavu:
    image: appbaseio/dejavu:3.3.0
    container_name: dejavu
    ports:
      - "${DEJAVU_PORT}:1358"
    depends_on:
      - elasticsearch
